app = "krakentime-winter-paper-1452"
primary_region = "cdg"  # ou "ams", "lhr", etc.

[build]

[env]
  DISCORD_TOKEN = "..."     # Tu peux aussi les définir via `fly secrets`
  CLIENT_ID = "..."
  CLIENT_SECRET = "..."
  SESSION_SECRET = "..."
  CALLBACK_URL = "https://nom-de-ton-app.fly.dev/auth/discord/callback"

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000
    grace_period = "10s"
    restart_limit = 0
